"""empty message

Revision ID: 48e11784bff1
Revises: 20d64a44b03f
Create Date: 2023-03-22 22:15:52.818197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e11784bff1'
down_revision = '20d64a44b03f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
